### ISSUE TITLE
Add instrument specific ATR flight-phase separation files

### ISSUE THREAD

**Issue by observingClouds** [eurec4a/flight-phase-separation#32]
Hi,

Over in https://github.com/eurec4a/eurec4a-intake/pull/158 the question was raised if it would be feasible to add the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/) that have been created for the isotope record to this flight-segmentation repository as they closely match its syntax.

An example file looks like

```
name: RF03 
mission: EUREC4A
flight_id: ATR-0126 
contacts:
- name: Author
  email: author@mail.com
date: 2020-01-26 
flight_report: https://observations.ipsl.fr/aeris/eurec4a-data/REPORTS/ATR-42/2020/20200126/ATR-0126.pdf 
takeoff: 2020-01-26 11:34:57 
landing: 2020-01-26 16:08:07 
events: []
remarks: 'synchronisation problem of Picarro with ATR core data, shifting during flight'
segments:
- kind: dry event
  name: D1
  start: 2020-01-26 15:46:00
  end: 2020-01-26 16:04:00
```

What would be needed to make these files available through the flight-segmentation API? Should the files be copied into this repo or could they be accessed from its current published location at https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/ ?
